app/cmd/preview.go, app/cmd/publish.go, app/cmd/root.go
https://www.pivotaltracker.com/story/show/169736001
=> Generate config if none exist#169736001

app/cmd/new.go, app/cmd/new_test.go, app/cmd/preview.go, app/cmd/root.go
https://www.pivotaltracker.com/story/show/170106232
=> Learn new cmd#170106232

app/cmd/config.go, app/cmd/preview.go
https://www.pivotaltracker.com/story/show/170581946
=> fix some wording

app/cmd/preview.go, app/cmd/root.go
https://www.pivotaltracker.com/story/show/170676339
=> add in open preview bool flag to force opening in browser

app/cmd/config.go, app/cmd/config_test.go, fixtures/test-block-no-config/autoconfig.yaml
https://www.pivotaltracker.com/story/show/170658823
=> parse out the file types and visibility from the filename

app/cmd/preview.go, app/cmd/preview_test.go, app/cmd/root.go, fixtures/test-links/nested/test.md
https://www.pivotaltracker.com/story/show/171986961
=> add sql files to preview

README.md, app/cmd/markdown.go, app/cmd/root.go
Enhances the markdown command with potent abilities
=> Snippets alt

app/cmd/config.go, app/cmd/publish.go
https://www.pivotaltracker.com/story/show/173270406
=> No message config file found#173270406

.gitignore, api/learn/build_test.go, api/learn/publish.go, app/cmd/publish.go, app/cmd/root.go, go.sum
https://www.pivotaltracker.com/story/show/172683539
=> break apart the repo and pass along pieces to publish block

app/cmd/config.go, app/cmd/root.go, fixtures/test-block-no-config/autoconfig.yaml
https://www.pivotaltracker.com/story/show/174804046
=> use a regex to find match of file types

app/cmd/publish.go, app/cmd/root.go
Solves https://www.pivotaltracker.com/story/show/175365678
=> strip ssh protocl from git remote when present

app/cmd/publish.go, app/cmd/root.go
https://www.pivotaltracker.com/story/show/176126648
=> return the git failure output when pushin

app/cmd/set.go
https://www.pivotaltracker.com/story/show/175820991
=> make set command fail with no flags provided

.goreleaser.yml, README.md, app/cmd/preview.go, app/cmd/root.go
=> adds windows compatibility#177154255

app/cmd/publish.go, app/cmd/root.go
https://www.pivotaltracker.com/story/show/177462561
=> Publish warns work not on remote

.gitignore, app/cmd/config.go, app/cmd/config_test.go, app/cmd/preview.go, app/cmd/root.go, fixtures/test-block-no-config/autoconfig.yaml, fixtures/test-block-no-config/units/01-checkpoint/another-checkpoint.md, go.mod, go.sum, mdresourceparser/md_resource_parser.go, mdresourceparser/md_resource_parser_test.go
https://www.pivotaltracker.com/story/show/177180439
=> remove md files from ignored paths

app/cmd/config.go
=> Fix typo in error message

app/cmd/preview.go, app/cmd/preview_test.go
https://www.pivotaltracker.com/story/show/178572859
=> Docker dir bug#178572859

upgrade_instructions.md
Simple fix that ensures we don't get strange problems with brew's local cache not updating and seeing more recent versions.
=> Brew's cache will sometimes get stuck without an update

app/cmd/markdown.go
Added distributecode to markdown.go
=> Add Distribute Code Button
